import { useEffect } from '@wordpress/element';
import { useSelect } from '@wordpress/data';
import { useSuggestionStore } from '@/apps/gutenberg-suggestions/stores/suggestionStore';

export const useSuggestionDetector = () => {
    const { setActiveSuggestion } = useSuggestionStore();

    const { selectedBlock, allBlocks } = useSelect((select) => {
        const {
            getSelectedBlock,
            getBlocks
        } = select('core/block-editor') as any;

        return {
            selectedBlock: getSelectedBlock(),
            allBlocks: getBlocks()
        };
    }, []);

    useEffect(() => {
        if (!selectedBlock) {
            return;
        }

        // Check for image block without alt text
        if (selectedBlock.name === 'core/image') {
            const { alt, url } = selectedBlock.attributes;

            if (url && (!alt || alt.trim() === '')) {
                const suggestion: Suggestion = {
                    id: `${selectedBlock.clientId}-alt-text`,
                    blockId: selectedBlock.clientId,
                    type: 'alt-text',
                    message: '🔍 This image needs alt text for better accessibility.',
                    suggestedValue: '', // Will be generated by AI
                    blockName: selectedBlock.name
                };

                setActiveSuggestion(suggestion);
                return;
            }
        }

        // Clear suggestion if selected block doesn't need one
        setActiveSuggestion(null);
    }, [selectedBlock, setActiveSuggestion]);
};